# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [svg, json]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        name: Check for Linting errors on MarkDown files
        exclude: .github/styles
        args:
          - --config=.github/.markdownlint.yaml
          - --fix

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.10.3
    hooks:
      - id: markdown-link-check
        name: Markdown Link Check
        description: Extracts links from markdown texts and checks they're all alive (i.e. return status 200 OK).
        entry: markdown-link-check
        language: node
        types: [markdown]
        stages: [commit, push, manual]
        args:
          - --quiet

  - repo: https://github.com/errata-ai/vale
    rev: ab5fe92
    hooks:
      - id: vale
        files: workshops/
